### ISSUE TITLE
多标签代码块生成错误

### ISSUE THREAD

**Issue by luiqn2007** [springtwr/siyuan-code-tabs#3]
思源版本：3.0.17
导入实例 Markdown 后生成后是类似这种效果：

![SiYuan_20240623_115](https://github.com/springtwr/siyuan-code-tabs/assets/18262245/782effe4-94af-4c6e-a5e2-83979145b27c)

**Comment by luiqn2007** [comment]
GIF 图片我这里显示不出来
![file-example](https://github.com/springtwr/siyuan-code-tabs/assets/18262245/f3a2e35b-efe8-4bde-a584-fbd93b7af854)

**Comment by springtwr** [comment]
> 思源版本：3.0.17 导入实例 Markdown 后生成后是类似这种效果：
> 
> ![SiYuan_20240623_115](https://private-user-images.githubusercontent.com/18262245/342059397-782effe4-94af-4c6e-a5e2-83979145b27c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzA0NTUsIm5iZiI6MTcxOTIzMDE1NSwicGF0aCI6Ii8xODI2MjI0NS8zNDIwNTkzOTctNzgyZWZmZTQtOTRhZi00YzZlLWE1ZTItODM5NzkxNDViMjdjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDExNTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMDQ0ZjhjZjhiYjNlOTcxMWI2YmJiZTY3YTE3NDNlYjM3ZDIxNmRkOGMzMTAxNzQ2NjViOTI4NTkwZDkzOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IDe959FcJCsV3qQsNrvFCvoGeqrGxQxOiVzmjgdUheg) [ ![SiYuan_20240623_115](https://private-user-images.githubusercontent.com/18262245/342059397-782effe4-94af-4c6e-a5e2-83979145b27c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzA0NTUsIm5iZiI6MTcxOTIzMDE1NSwicGF0aCI6Ii8xODI2MjI0NS8zNDIwNTkzOTctNzgyZWZmZTQtOTRhZi00YzZlLWE1ZTItODM5NzkxNDViMjdjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDExNTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMDQ0ZjhjZjhiYjNlOTcxMWI2YmJiZTY3YTE3NDNlYjM3ZDIxNmRkOGMzMTAxNzQ2NjViOTI4NTkwZDkzOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IDe959FcJCsV3qQsNrvFCvoGeqrGxQxOiVzmjgdUheg) ](https://private-user-images.githubusercontent.com/18262245/342059397-782effe4-94af-4c6e-a5e2-83979145b27c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzA0NTUsIm5iZiI6MTcxOTIzMDE1NSwicGF0aCI6Ii8xODI2MjI0NS8zNDIwNTkzOTctNzgyZWZmZTQtOTRhZi00YzZlLWE1ZTItODM5NzkxNDViMjdjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDExNTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMDQ0ZjhjZjhiYjNlOTcxMWI2YmJiZTY3YTE3NDNlYjM3ZDIxNmRkOGMzMTAxNzQ2NjViOTI4NTkwZDkzOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IDe959FcJCsV3qQsNrvFCvoGeqrGxQxOiVzmjgdUheg) [ ](https://private-user-images.githubusercontent.com/18262245/342059397-782effe4-94af-4c6e-a5e2-83979145b27c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzA0NTUsIm5iZiI6MTcxOTIzMDE1NSwicGF0aCI6Ii8xODI2MjI0NS8zNDIwNTkzOTctNzgyZWZmZTQtOTRhZi00YzZlLWE1ZTItODM5NzkxNDViMjdjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDExNTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMDQ0ZjhjZjhiYjNlOTcxMWI2YmJiZTY3YTE3NDNlYjM3ZDIxNmRkOGMzMTAxNzQ2NjViOTI4NTkwZDkzOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IDe959FcJCsV3qQsNrvFCvoGeqrGxQxOiVzmjgdUheg)

这个看起来是脚本和样式没起作用， 在系统设置里面打开允许执行html块内脚本的开关了吗？

**Comment by luiqn2007** [comment]
确实是因为没开，问题解决
